### ISSUE TITLE
Please update the stuff

### ISSUE THREAD

**Issue by Jordan231111** [OnlineHacKing/Cloud_Linux_RDP#2]
A lot of the software/operating system used in the script seems to be out of date. It would be useful if you could look through all the code and update the things that need update.

**Comment by OnlineHacKing** [comment]
ok wait 1 day

**Comment by Jordan231111** [comment]
Are you updating it now because nothing is working as of now.
 bash: RDP/.ubuntu-desktop-lxde-vnc.sh: No such file or directory

**Comment by Jordan231111** [comment]
Feedback: I am still getting a lot of error with this key. Also I hope you are still considering adding newer operating system such as ubuntu 22.04 or above

**Comment by OnlineHacKing** [comment]
tool update finish

**Comment by Jordan231111** [comment]
> tool update finish

can you update ngrok to the latest which i think is 3.1.1
![opera_p7gpVdcQq2](https://user-images.githubusercontent.com/79342877/224504927-84201ca6-1911-472a-b605-47972ebefa41.png)

**Comment by Jordan231111** [comment]
Also running sudo apt upgrade
breaks the xorg rdp in kali linux
