### ISSUE TITLE
kali linux

### ISSUE THREAD

**Issue by Jordan231111** [OnlineHacKing/Cloud_Linux_RDP#3]
Is it possible for you to make the kali linux using novnc like option 6 on http port and not use xorg, xrdp, etc.

**Comment by Jordan231111** [comment]
Ok I did some more testing and what I want to do works with nomachine kali but can you please remove the 43200 seconds time limit or make it 9999999999s like the other rdp

**Comment by Allicss1** [comment]
Н

**Comment by Allicss1** [comment]
Н

**Comment by OnlineHacKing** [comment]
not working in novnc
